### ISSUE TITLE
Contract doesn't compile

### ISSUE THREAD

**Issue by seniorjoinu** [everx-labs/TVM-Solidity-Compiler#2] opened 2019-12-12 11:04 UTC
Hello there!
Here I have an example of contract that will compile using real eth-solc, but does not compile with this compiler.

```solidity
pragma solidity ^0.5.0;

contract Simple {
    bytes byteArray;

    function not_working() public {
        /* Require with text */
        require(true, "This message can be string in soliditiy");

        /* String <-> Bytes interop */
        byteArray = "string";

        /* Inline assembly */
        string memory str = "another string";
        uint ptr;
        assembly {
            ptr := add(str, 0x20)
        }

        /* Two-dimensional array */
        uint[][] memory testArray = new uint[][](10);
        require(testArray.length == 0);
    }
}
```

There are four sections (marked with a block comment each). Each section by itself produces a different error message (sometimes empty). 

Is there a bug tracker, where I can submit these bugs, somewhere? 
When can we expect these bugs to be fixed?
Is there a plan to make this compiler fully compatible with eth-solc (and if there is, when you expect it happen)?

**Comment by BorisI** [comment] 2019-12-13 12:00
Hi there and thanks for you feedback!

> Is there a plan to make this compiler fully compatible with eth-solc (and if there is, when you expect it happen)?

The main goal is to make this compiler suitable for programming for TON in Solidity. We don't plan to make it fully compatible with eth-solc.
TON is different from Ethereum, and TVM is totally different from EVM. Striving for full compatibility is going to be extremely hard, and at the same time very inefficient.
One of the goals of this compiler is to help migrating from ETH to TON with as little effort as possible.
Another goal of this compiler is to be efficient for developing contracts from scratch for those familiar with Solidity (or any kind of Javascript-like) language.

Let me answer your questions below:

> require(true, "This message can be string in soliditiy");

We extended `require()` with a numeric parameter because it makes sense for TON (utilizing THROWIFNOT command in TVM with an error code).
String parameter makes no sense for TON since there is no feasible way to pass that string through the exception handling machinery.
For the code above, currently we produce an error notifying user that string can be replaced with an error code number.
We consider changing error to warning about skipping the specified string parameter.

> byteArray = "string";

Should be working with latest compiler published yesterday (version 0.17).

> /* Inline assembly */

We have no plans to support EVM assembly - it just won't be efficient at all.  We are exposing some of TVM functionality as intrinsic functions, though.

```
> uint[][] memory testArray = new uint[][](10);
```

Thanks! Confirming a bug with two dimensional arrays with constructors. We plan to fix it in the upcoming releases.

> Is there a bug tracker, where I can submit these bugs, somewhere?

For the time being, please use this site. We also have telegram channels for general questions and discussions - TON.Dev En/Ru.

> When can we expect these bugs to be fixed?

Soon (TM). Generally we release fixes and features in batches, after testing against the rest of our technology stack. For urgent hotfixes, it might be as fast as 1-2 days.

Again, thank you very much for your feedback! Much appreciated.

Best regards,
sol2tvm compiler team

**Comment by seniorjoinu** [comment] 2019-12-14 14:01
Thanks for the reply, @BorisI! Glad I could help.
I'll try the new compiler version and report results at the beginning of the next week. 

One more question. I have a big smart-contract (about 9kb compiled with sol2tvm). But it seems like the Node (from Node SE kit) doesn't like its size. 
When I try to deploy it I get the next error "Create deploy message failed: cell overflow". Can you help me with it?

I'm only diving into this TON-world (currently I'm reading the papers and trying out some stuff with funC and your software), but it seems like big data chunks (my contract) should be split into cell tree and there shouldn't be any problem with its size.

**Comment by seniorjoinu** [comment] 2019-12-14 14:14
> Should be working with latest compiler published yesterday (version 0.17).

Looks like you didn't publish it on docker hub yet - it says that the compiler's image were updated 17 days ago. https://hub.docker.com/search?q=tonlabs

**Comment by buktop24** [comment] 2019-12-14 20:11
> When I try to deploy it I get the next error "Create deploy message failed: cell overflow". Can you help me with it?

Hi! Could you please provide constructor parameter types and the actual values you are passing to?

**Comment by seniorjoinu** [comment] 2019-12-16 09:16
Hello, @buktop24!

Here is the contract's constructor in solidity
```solidity
constructor(
  uint160[2] memory parents,
  uint64[2] memory timestamps,
  uint32 amount,
  uint8[] memory details,
  uint8[] memory detailsDelimiter
) public {
  ...
}
```

Here is my contract deployment script in js
```js
const {TONClient} = require('ton-client-node-js');

async function main(client) {
  const constructorParams = {
    parents: [1234, 1234],
    timestamps: [1234, 1234],
    amount: 1234,
    details: [123, 1, 123, 1, 123, 1, 123, 1, 123],
    detailsDelimiter: [1],
  };

  const helloKeys = await client.crypto.ed25519Keypair();

  const goalAddress = (await client.contracts.deploy({
    package: GoalContract.package,
    constructorParams,
    keyPair: helloKeys,
  })).address;
  console.log(`Goal contract was deployed at address: ${goalAddress}`);

  const response = await client.contracts.run({
    address: goalAddress,
    abi: GoalContract.package.abi,
    functionName: 'getData',
    input: {},
    keyPair: helloKeys,
  });
  console.log('Goal contract was responded to getData:', response);
}

(async () => {
  try {
    const client = new TONClient();
    client.config.setData({
      servers: ['http://0.0.0.0'],
    });
    await client.setup();
    await main(client);
    console.log('Hello TON Done');
    process.exit(0);
  } catch (error) {
    console.error(error);
  }
})();
```

**Comment by BorisI** [comment] 2019-12-17 16:22
> When I try to deploy it I get the next error "Create deploy message failed: cell overflow". Can you help me with it?

Confirming a bug on our side, in contract deployment machinery. We expect it to be fixed in the upcoming release (likely next week). For the time being, it can be worked around by passing two last parameters separately, not as a part of the constructor message.

**Comment by BorisI** [comment] 2020-01-17 14:15
On the reported problems:
#1 - works as intended; use numerical code to specify the nature of exception;
#2 - fixed, works in the current release;
#3 - not applicable to TON, will not be supported;
#4 - fixed, works in the current release.
problem with contract deployment - fixed in the upcoming release.

**Closed as completed by BorisI** 2020-01-17 14:15 UTC
